        stdClass::__set_state(
        array(
        'name' => 'gfdfhg',
        'mform_isexpanded_id_availability' => 1,
        'allowsubmissionsfromdate' => 1409155200,
        'duedate' => 1409760000,
        'cutoffdate' => 0,
        'alwaysshowdescription' => '1',
        'assignsubmission_comments_enabled' => 1,
        'assignsubmission_file_enabled' => '1',
        'assignsubmission_codehandin_enabled' => '1',
        'assignsubmission_file_maxfiles' => '1',
        'assignsubmission_file_maxsizebytes' => '5242880',
        'assignsubmission_onlinetext_wordlimit' => '',
		
		
        'proglang' => '3',
        'mustattemptcompile' => '1',
        'cpname' => 'appl',
        'cpordering' => 1,
        'cpdescription' => array (
        'text' => 'fdg',
        'format' => '1',
        'itemid' => 263549805, ),
        'cpruntimeargs' => '',
        'taskname' => '',
        'taskordering' => 1,
        'taskdescription' => '',
        'taskruntimeargs' => '',
        'taskretval' => 0,
        'taskinput' => '666168213',
        'taskoutput' => '35949707',
        'taskstderr' => '139007569',
		
		
        'assignfeedback_comments_enabled' => '1',
        'assignfeedback_comments_commentinline' => '0',
        'mform_isexpanded_id_submissiontypes' => 1,
        'submissiondrafts' => '0',
        'requiresubmissionstatement' => '0',
        'attemptreopenmethod' => 'none',
        'maxattempts' => '-1',
        'teamsubmission' => '0',
        'requireallteammemberssubmit' => '0',
        'sendnotifications' => '0',
        'sendlatenotifications' => '0',
        'sendstudentnotifications' => '1',
        'grade' => 100,
        'advancedgradingmethod_submissions' => '',
        'gradecat' => '2',
        'blindmarking' => '0',
        'markingworkflow' => '0',
        'markingallocation' => '0',
        'visible' => '1',
        'cmidnumber' => '',
        'groupmode' => '0',
        'groupingid' => '0',
        'course' => '2',
        'coursemodule' => 69,
        'section' => 6,
        'module' => 1,
        'modulename' => 'assign',
        'instance' => '',
        'add' => 'assign',
        'update' => 0,
        'return' => 0,
        'sr' => 0,
        'submitbutton2' => 'Save and return to course',
        'groupmembersonly' => 0,
        'completion' => 0,
        'completionview' => 0,
        'completionexpected' => 0,
        'completiongradeitemnumber' => NULL,
        'conditiongradegroup' => array ( ),
        'conditionfieldgroup' => array ( ),
        'intro' => 'dfgdg',
        'introformat' => '1',
        ))